# Generated by Django 5.2.5 on 2025-09-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Статус оплаты в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Stripe Session ID"
            ),
        ),
    ]
