# Generated by Django 5.2.5 on 2025-08-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_auto_20250830_1451"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AddField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                default=1,
                help_text="Введите название курса",
                max_length=200,
                verbose_name="Курс",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Расскажите о своём курсе",
                null=True,
                verbose_name="Описание курса",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку курса",
                null=True,
                upload_to="study/previews",
                verbose_name="Картинка",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="study.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_description",
            field=models.TextField(
                default=1,
                help_text="Расскажите об уроке",
                verbose_name="Описание урока",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_name",
            field=models.CharField(
                default=1,
                help_text="Введите название урока",
                max_length=250,
                verbose_name="Урок",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="preview_l",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите картинку урока",
                null=True,
                upload_to="study/preview_l",
                verbose_name="Картинка",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_link",
            field=models.TextField(
                blank=True,
                help_text="Введите ссылку на видео",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
