# Generated by Django 5.2.5 on 2025-09-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["id"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
