# Generated by Django 5.2.5 on 2025-09-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0007_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите стоимость курса в рублях",
                max_digits=10,
                verbose_name="Цена курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите стоимость урока в рублях",
                max_digits=10,
                verbose_name="Цена урока",
            ),
        ),
    ]
